#!/bin/sh

mkdir -p generated_models
mkdir -p generated_libraries

for i in client_ech client server
do
  m4 libraries/$i.m4.pvl > generated_libraries/$i.pvl
  m4 -D NOHRR libraries/$i.m4.pvl > generated_libraries/"$i"_NOHRR.pvl
done

for i in SCENARIO1 SCENARIO2 SCENARIO3 SCENARIO4 SCENARIO5
do
    m4 -D$i privacy_backend.m4.pv > generated_models/privacy_backend_$i.pv
    m4 -D$i privacy_client_ech.m4.pv > generated_models/privacy_client_ech_$i.pv
    m4 -D$i privacy_client.m4.pv > generated_models/privacy_client_$i.pv
    m4 -D$i strong_secrecy_inner.m4.pv > generated_models/strong_secrecy_inner_$i.pv
    m4 -D$i real_or_random_psk.m4.pv > generated_models/real_or_random_psk_$i.pv
done

for i in tls_C_tls_S tls_C_ech_S ech_C_tls_S ech_C_ech_S grease_C_tls_S grease_C_ech_S
do
    m4 -D$i sanity_checks.m4.pv > generated_models/sanity_checks_$i.pv
done
